### PR TITLE
Removed `node-fetch` library

### PR DESCRIPTION
**Pull request by c4ldas**

### CODE REVIEW

**Review by igorfernandescordeiro — APPROVED** [review]
More clean up but what are you using to fetch the data ?

**Comment by c4ldas** [comment]
fetch()

**Comment by igorfernandescordeiro** [comment]
This fetch() is from JavaScript itself right? I used in yesterday in one of my study codes

**Comment by c4ldas** [comment]
Yeah, nodejs didn't have a native fetch lib when I started with the API.
But now I don't need a separated lib for that anymore.

**Pull request merged**
